name: Deploy All Services to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-all:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push all services
        run: |
          SERVICES=("user-service" "board-service" "product-service" "config-service" "discovery-service" "gateway-service" "transaction-service")

          for SERVICE in "${SERVICES[@]}"; do
            IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVICE
            echo "🔨 Building and pushing $SERVICE -> $IMAGE_URI"
            docker build -t $IMAGE_URI ./$SERVICE
            docker push $IMAGE_URI
          done
